/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebankaccesobd;

import java.sql.SQLException;

/**
 *
 * @author Nocturno
 */
public class AccesoCuentasClienteComboBox extends javax.swing.JDialog {

    Banco eBanco;
    Cliente cliente;
    CuentasPorCliente tCuentas;
    
    public AccesoCuentasClienteComboBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AccesoCuentasClienteComboBox(java.awt.Frame parent, boolean modal, Banco banco, Cliente cli) throws SQLException {
        super(parent, modal);
        eBanco = banco;
        cliente = cli;
        
        tCuentas = eBanco.obtenerCuentasCliente(cli.getDNI());
        initComponents();
        
        formateaComboBox();
        
        
    }
    
    public void formateaComboBox(){
        
        if (tCuentas.gettTarjetas()==null) {
            tCuentasCombojComboBox1.addItem("El cliente seleccionado no tiene cuentas asociadas");
        }else{
            for (int i = 0; i < tCuentas.gettTarjetas().size(); i++) {
            tCuentasCombojComboBox1.addItem(tCuentas.gettTarjetas().get(i).formateaNumeroTarjeta());
            
            }            
        }   
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dniJLabel = new javax.swing.JLabel();
        nombreJLabel = new javax.swing.JLabel();
        tCuentasCombojComboBox1 = new javax.swing.JComboBox<>();
        modificarjButton = new javax.swing.JButton();
        bajajButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI:");

        jLabel2.setText("Nombre:");

        dniJLabel.setText(cliente.getDNI());

        nombreJLabel.setText(cliente.getNombre());

        tCuentasCombojComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCuentasCombojComboBox1ActionPerformed(evt);
            }
        });

        modificarjButton.setText("Modificar");
        modificarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarjButtonActionPerformed(evt);
            }
        });

        bajajButton.setText("Baja");
        bajajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dniJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(tCuentasCombojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificarjButton)
                .addGap(80, 80, 80)
                .addComponent(bajajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dniJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tCuentasCombojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarjButton)
                    .addComponent(bajajButton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCuentasCombojComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCuentasCombojComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCuentasCombojComboBox1ActionPerformed

    private void modificarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarjButtonActionPerformed
        // TODO add your handling code here:
        TarjetaCredito tar = null;
        tar = tCuentas.gettTarjetas().get(tCuentasCombojComboBox1.getSelectedIndex());
        ModificarBorrarTarjetaJDialog modifica = new ModificarBorrarTarjetaJDialog(null, "Modificación", eBanco, tar);
        modifica.setVisible(true);
        
        
    }//GEN-LAST:event_modificarjButtonActionPerformed

    private void bajajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajajButtonActionPerformed
        TarjetaCredito tar = null;
        tar = tCuentas.gettTarjetas().get(tCuentasCombojComboBox1.getSelectedIndex());
        ModificarBorrarTarjetaJDialog borra = new ModificarBorrarTarjetaJDialog(null, "Dar de Baja", eBanco, tar);
        borra.setVisible(true);
        
    }//GEN-LAST:event_bajajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoCuentasClienteComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoCuentasClienteComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoCuentasClienteComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoCuentasClienteComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccesoCuentasClienteComboBox dialog = new AccesoCuentasClienteComboBox(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajajButton;
    private javax.swing.JLabel dniJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modificarjButton;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JComboBox<String> tCuentasCombojComboBox1;
    // End of variables declaration//GEN-END:variables
}
