/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebankaccesobd;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LilCucumbah
 */
public class DNIgenerator extends javax.swing.JDialog {

    Banco eBanco = null;
    
    public DNIgenerator(java.awt.Frame parent, boolean modal, Banco banco) {
        super(parent, modal);
        eBanco = banco;
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }
    public DNIgenerator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letraJLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dniJTextField = new javax.swing.JTextField();
        copiarjButton = new javax.swing.JButton();
        borrarButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        letraJLabel11.setText(" ");

        jLabel1.setText("DNI");

        dniJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dniJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniJTextFieldActionPerformed(evt);
            }
        });

        copiarjButton.setText("Copiar");
        copiarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarjButtonActionPerformed(evt);
            }
        });

        borrarButton2.setText("Borrar");
        borrarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copiarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(dniJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(letraJLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dniJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraJLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copiarjButton)
                    .addComponent(borrarButton2))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniJTextFieldActionPerformed

        String dni = dniJTextField.getText();

        try {
            if(dni.length()== 0){
                javax.swing.JOptionPane.showMessageDialog(null, "Error, el campo DNI está vacío");
            }else if (dni.length()<8 ||dni.length() > 8) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error, el numero de DNI se compone exactamente de 8 dígitos");
            } else {
                boolean nifValido =false;
                for (int i = 0; i < dni.length(); i++) {

                    nifValido = FuncionesSobreCaracteres.esNumeroValido(dni.charAt(i));
                }
                if (!nifValido) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Error, en el numero del dni solo ha de introducir digitos del 0-9");
                }else{
                    letraJLabel11.setText(Cliente.asignaLetraDNI(dni));
                    dni += letraJLabel11.getText();

                    if (eBanco.buscaDNICliente(dni) != null) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Error, ese DNI ya está"
                            + " dado de alta como cliente, por favor prube con otro DNI");
                    }else{
                        dniJTextField.setBackground(Color.green);
                        dniJTextField.setEditable(false);
                    }
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(BancoConIgSerializado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dniJTextFieldActionPerformed

    private void copiarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarjButtonActionPerformed
        // TODO add your handling code here:
        
        String dniCompleto = dniJTextField.getText()+letraJLabel11.getText();
        StringSelection seleccionString = new StringSelection (dniCompleto);
        Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
        portapapeles.setContents(seleccionString, null);
        
        dispose();        
        
    }//GEN-LAST:event_copiarjButtonActionPerformed

    private void borrarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButton2ActionPerformed
        dniJTextField.setText("");
        dniJTextField.setBackground(Color.white);
        dniJTextField.setEditable(true);
        
    }//GEN-LAST:event_borrarButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DNIgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DNIgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DNIgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DNIgenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DNIgenerator dialog = new DNIgenerator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarButton2;
    private javax.swing.JButton copiarjButton;
    private javax.swing.JTextField dniJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letraJLabel11;
    // End of variables declaration//GEN-END:variables
}
